########################################################################
#
# title:       Docker Compose YAML file for spring-music
# author:      Gary A. Stafford (https://programmaticponderings.com)
# url:         https://github.com/garystafford/spring-music-docker.git  
# description: Builds multi-VM Docker Swarm cluster, 'Producion' environment,
#              using (2) pre-built images, located on Docker Hub
# to run:      docker-compose -f docker-compose-swarm.yml -p music up -d
# to scale:    docker-compose -f docker-compose-swarm.yml -p music scale app=2 up -d
#
########################################################################


### NOT FINISHED - DO NOT USE ###


proxy:
  image: garystafford/spring-music-docker-nginx
  ports:
   - "80:80"
  hostname: "proxy"
  environment:
   - "constraint:itype==proxy"
   - "TERM=xterm"

app:
  image: garystafford/spring-music-docker-tomcat
  ports:
   - "8080"
  hostname: "app"
  environment:
   - "constraint:itype==app"

nosqldb:
  image: garystafford/spring-music-docker-mongo
  ports:
   - "27017"
  hostname: "nosqldb"
  environment:
    - "constraint:itype==nosqldb"

elk:
  image: garystafford/spring-music-docker-elk
  ports:
   - "8081:80"
   - "8082:9200"
  expose:
    - "5000/upd"
  environment:
   - "constraint:itype==logging"

logspout:
  image: garystafford/spring-music-docker-logspout
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  ports:
   - "8083:80"
  environment:
   - ROUTE_URIS=logstash://music_elk_1:5000
   - "constraint:itype==logging"