########################################################################
#
# title:       Docker Compose YAML file for spring-music
# author:      Gary A. Stafford (https://programmaticponderings.com)
# url:         https://github.com/garystafford/spring-music-docker.git  
# description: Builds single VM, multi-container environment
#              with debugging ports open and extra header information
# to run:      docker-compose -f docker-compose.yml -p music up -d
#
########################################################################

proxy:
  build: nginx/
  ports:
   - "80:80"

app01:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8180:8080"

app02:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8280:8080"

nosqldb:
  build: mongo/
  volumes:
   - "/opt/mongodb:/data/db"

elk:
  build: elk/
  ports:
   - "8081:80"
   - "8082:9200"
  expose:
   - "5000/upd"

logspout:
  build: logspout/
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  ports:
   - "8083:80"
  environment:
    - ROUTE_URIS=logstash://music_elk_1:5000