version: '2'

services:
  proxy:
    build: nginx/
    ports:
    - 80:80
    depends_on:
    - app01
    - app02
    hostname: proxy
    container_name: proxy

  app01:
    build: tomcat/
    ports:
    - 8180:8080
    depends_on:
    - mongodb
    hostname: app01
    container_name: app01

  app02:
    build: tomcat/
    ports:
    - 8280:8080
    depends_on:
    - mongodb
    hostname: app02
    container_name: app02

  mongodb:
    build: mongodb/
    depends_on:
    - elk
    hostname: mongodb
    container_name: mongodb
    volumes:
    - music_data:/data/db:rw
    - music_data:/data/configdb:rw

  elk:
    image: sebp/elk:latest
    ports:
    - 5601:5601
    - 9200:9200
    - 5044:5044
    - 5000:5000
    hostname: elk
    container_name: elk

volumes:
  music_data:
    external: true

networks: {}
